#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  guifont = "Hack"
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  # enable_statusline_mode = true
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  # enable_vimfiler_gitstatus = true
  buffer_index_type = 4
  enable_statusline_display_mode = true
  enable_tabline_filetype_icon = true
  enable_os_fileformat_icon = true
  enable_neomake = true
  autocomplete_method = "coc"
  autocomplete_parens = true
  snippet_engine = "ultisnips"
  lint_on_the_fly = true

  filemanager = "nerdtree"
  filetree_direction = "left"
  
  sidebar_width = 20
  sidebar_direction = 'right'

  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"
  automatic_update = true

[[layers]]
  name = "ui"
  enable_sidebar = true

[[layers]]
  name = "VersionControl"

[[layers]]
name = "ctrlp"

[[layers]]
  name = "git"

[[layers]]
  name = "unite"

[[layers]]
  name = "checkers"
  show_cursor_error = true

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "nil"
  auto_completion_tab_key_behavior = "smart"
  # auto-completion-complete-with-key-sequence = "nil"

[[layers]]
  name = "debug"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "sudo"

[[layers]]
  name = "lang#markdown"
  enabled_formater = 'prettier'

[[layers]]
  name = "lang#toml"
  enabled_formater = 'prettier'

[[layers]] 
  name = 'lsp'
  filetypes = [
    'sh',
    'javascript',
    'typescript',
    'svelte'
  ]
  [layers.override_cmd]
    c = ['ccls', '--log-file=/tmp/ccls.log']
    cpp = ['ccls', '--log-file=/tmp/ccls.log']

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lang#svelte"

[[layers]]
  name = "lang#python"
  enable_typeinfo = true

[[layers]]
  name = "lang#ipynb"

[[layers]]
  name = "lang#java"

[[custom_plugins]]
  # name = 'pearofducks/ansible-vim'
  # name = 'evanleck/vim-svelte'
  # name = 'lambdalisue/vim-pyenv'
  # name =  "leafOfTree/vim-svelte-plugin"
  # repo = 'codechips/coc-svelte'
  # on_cmd = [ 'npm install' ]
  name = 'codechips/coc-svelte'
  # repo =  "norcalli/nvim-colorizer.lua"
  # on_cmd = ["ColorizerToggle"]
  repo =  "rrethy/vim-hexokinase"
  on_cmd = ["make hexokinase"]
  # repo = "lilydjwg/colorizer"
  # on_cmd = ["ColorHighlight", "ColorToggle"]
  # merged = false
  # repo = 'glacambre/firenvim'
  # on_cmd = "firenvim#install(0)"
